# Generated by Django 2.2.5 on 2019-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('partener', models.TextField()),
                ('type_of_model', models.TextField()),
                ('time_horizon', models.IntegerField()),
                ('time_steps_in_solution', models.IntegerField()),
                ('model_descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Socioecons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('subcategory', models.TextField(default='')),
                ('socioecon', models.TextField()),
                ('state', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('subcategory', models.TextField(default='')),
                ('sector', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sdgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_name', models.TextField()),
                ('description', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('policy', models.TextField()),
                ('state', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('subcategory', models.TextField(default='')),
                ('measure', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField()),
                ('emission', models.TextField()),
                ('state', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField()),
                ('country_code', models.CharField(max_length=3)),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
                ('region', models.ManyToManyField(to='i2amparis_main.Regions')),
            ],
        ),
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('measure', models.TextField()),
                ('model_name', models.ManyToManyField(to='i2amparis_main.ModelsInfo')),
            ],
        ),
    ]
