# Generated by Django 2.2.5 on 2019-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2amparis_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptation',
            old_name='measure',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='emissions',
            old_name='emission',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mitigations',
            old_name='measure',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='policies',
            old_name='policy',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sdgs',
            old_name='sdg_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sectors',
            old_name='sector',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='socioecons',
            old_name='socioecon',
            new_name='name',
        ),
        migrations.AddField(
            model_name='regions',
            name='descr',
            field=models.TextField(default=''),
        ),
    ]
