version: '3'

networks:
  config_i2amparis:
    external: true

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - i2amparis
    restart: "on-failure"

  i2amparis_db:
    build: .
    hostname: ${POSTGRESS_HOST}
    container_name: ${POSTGRESS_HOST}
    restart: always
    command: ["-c", "shared_buffers=3GB", "-c", "max_connections=1000", "-c", "idle_in_transaction_session_timeout=1min"]
    ports:
      - 5435:5432
    volumes:
      - i2amparis_db_volume:/var/lib/postgresql/data
      - ../db_new.sqlite3:/var/lib/sqlite3/db_new.sqlite3
      - ./migration_from_sqlite3_to_postgres_command:/migration_from_sqlite3_to_postgres_command
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    networks:
      - config_i2amparis

  i2amparis:
    container_name: ${PARIS_HOSTNAME}
    hostname: ${PARIS_HOSTNAME}
    restart: always
    networks:
      - config_i2amparis
    build:
      context: ".."
      dockerfile: config/Dockerfile
      args:
        SETTINGS: ${SETTINGS}
        PORT: ${PORT}
    command:
    ports:
      - ${PORT}:${PORT}
    environment:
      SETTINGS: ${SETTINGS}
      PORT: ${PORT}
      POSTGRESS_USER: ${POSTGRESS_USER}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      POSTGRESS_PORT: ${POSTGRESS_PORT}
      POSTGRESS_DB: ${POSTGRESS_DB}
    depends_on:
      - i2amparis_db
