version: '3'


services:
  nginx-proxy:
    container_name: i2amparis_nginx
    build:
      context: "."
      dockerfile: "./nginx/Dockerfile"
    volumes:
      - static_volume:/home/i2amparis/web/staticfiles
      - www-certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - ../.env/prod/.env.staging.proxy-companion
    depends_on:
      - i2amparis


  i2amparis:
    container_name: ${APP_HOSTNAME}
    hostname: ${APP_HOSTNAME}
    build:
      context: ".."
      dockerfile: "./config_prod/Dockerfile"
      args:
        SETTINGS: ${SETTINGS}
        PORT: ${PORT}
    volumes:
      - static_volume:/home/i2amparis/web/staticfiles
    expose:
      - ${PORT}
    env_file:
      - ../.env/prod/.env_app_prod
    depends_on:
      - i2amparis_db

  i2amparis_db:
    image: postgres:13.0-alpine
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    command: ["-c", "shared_buffers=3GB", "-c", "max_connections=1000", "-c", "idle_in_transaction_session_timeout=1min"]
    ports:
      - 5555:5432
    volumes:
      - i2amparis_db_prod_data:/var/lib/postgresql/data
    env_file:
      - ../.env/prod/.env_db_prod

volumes:
  i2amparis_db_prod_data:
  static_volume:
  www-certs:


